name: Github Action for a Dojo Update
description: GitHub Action for a dojo update
author: pwn.college
inputs:
  site:
    description: The site hosting the dojo
    default: https://pwn.college
  dojo:
    description: The reference id of the dojo
    required: true
  update_code:
    description: The update code of the dojo
    required: true
runs:
  using: docker
  image: docker://alpine/curl:latest
  args:
    - --silent
    - --fail-with-body
    - --request
    - POST
    - ${{ inputs.site }}/dojo/${{ inputs.dojo }}/update/${{ inputs.update_code }}
branding:
  icon: arrow-up
  color: blue
